In [1]:
import pandas as pd

In [6]:
diamonds = pd.read_csv('rick_diamonds.csv')
diamonds

      carat        cut color clarity  depth  table     x     y     z
0      0.91  Very Good     H     SI2   63.4   57.0  6.10  6.18  3.89
1      0.38       Good     F     VS2   60.3   61.0  4.68  4.71  2.83
2      0.52      Ideal     H     VS2   61.8   56.0  5.19  5.16  3.20
3      1.10      Ideal     G     VS1   61.3   56.0  6.65  6.69  4.09
4      2.28      Ideal     G     SI2   61.6   57.0  8.44  8.37  5.18
...     ...        ...   ...     ...    ...    ...   ...   ...   ...
4995   0.30  Very Good     D     SI2   62.2   59.0  4.25  4.30  2.66
4996   0.51      Ideal     F    VVS2   61.9   56.0  5.09  5.14  3.16
4997   1.01  Very Good     F     SI1   60.6   60.0  6.37  6.43  3.88
4998   0.31      Ideal     F    VVS1   62.1   56.0  4.35  4.38  2.71
4999   0.33      Ideal     E     VS2   61.8   55.0  4.45  4.48  2.76

[5000 rows x 9 columns]

In [7]:
cuts = list(diamonds['cut'].value_counts().index)
cuts.reverse()
n_cut={}
for item in cuts:
    n_cut.update({item:cuts.index(item)})

In [10]:
colors = list(diamonds['color'].value_counts().index)
colors.sort()
colors.reverse()
n_color = {}
for item in colors:
    n_color.update({item:colors.index(item)})

In [13]:
clarity = ['I1' , 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']
n_clarity = {}
for item in clarity:
    n_clarity.update({item:clarity.index(item)})

In [14]:
diamonds['n_cut'] = diamonds['cut'].map(n_cut)
diamonds['n_color'] = diamonds['color'].map(n_color)
diamonds['n_clarity'] = diamonds['clarity'].map(n_clarity)

In [15]:
diamonds

,carat,cut,color,clarity,depth,table,x,y,z,n_cut,n_color,n_clarity
0,0.91,Very Good,H,SI2,63.4,57.0,6.10,6.18,3.89,2,2,1
1,0.38,Good,F,VS2,60.3,61.0,4.68,4.71,2.83,1,4,3
2,0.52,Ideal,H,VS2,61.8,56.0,5.19,5.16,3.20,4,2,3
3,1.10,Ideal,G,VS1,61.3,56.0,6.65,6.69,4.09,4,3,4
4,2.28,Ideal,G,SI2,61.6,57.0,8.44,8.37,5.18,4,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.30,Very Good,D,SI2,62.2,59.0,4.25,4.30,2.66,2,6,1
4996,0.51,Ideal,F,VVS2,61.9,56.0,5.09,5.14,3.16,4,4,5
4997,1.01,Very Good,F,SI1,60.6,60.0,6.37,6.43,3.88,2,4,2
4998,0.31,Ideal,F,VVS1,62.1,56.0,4.35,4.38,2.71,4,4,6
4999,0.33,Ideal,E,VS2,61.8,55.0,4.45,4.48,2.76,4,5,3

In [22]:
diamonds.to_csv('rick.csv')